@startuml
hide footbox
actor User
participant ":Parser"
participant ":DeleteByIndexCommand"
participant ":Library"
participant ":CatalogueManager"
participant ":ShelvesManager"
participant ":Storage"
participant ":Ui"

User -> ":Parser" : input "delete num/1"
":Parser" -> ":DeleteByIndexCommand" : create command
":DeleteByIndexCommand" -> ":Library" : execute(bookIndex)
":Library" -> ":CatalogueManager" : deleteBook(bookIndex)
":CatalogueManager" --> ":Library" : response (bookDeleted)
":Library" -> ":ShelvesManager" : deleteBook(bookID)
":Library" --> ":DeleteByIndexCommand" : return response
":DeleteByIndexCommand" -> ":Storage" : update storage
":DeleteByIndexCommand" -> ":Ui": pass response
":Ui" --> User: prints response

@enduml
