@startuml
hide circle
skinparam classAttributeIconSize 0

class Storage {
    - final ShelvesManager shelvesManager

    + List<Book> loadFileContents(MemberManager memberManager)
    + void writeToFile(List<Book> bookList)
}

class ShelvesManager {
}

class MemberManager {
}

class Book {
}

Storage --> ShelvesManager : uses
Storage --> MemberManager : uses
Storage --> Book : instantiates
@enduml